In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [7]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [8]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9833333333333333

In [9]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8462962962962963

In [13]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
get_score(SVC(), X_train, y_train, X_test, y_test)

0.9833333333333333

In [15]:
get_score(RandomForestClassifier(), X_train, y_train, X_test, y_test)

0.975925925925926

In [16]:
get_score(LogisticRegression(), X_train, y_train, X_test, y_test)

c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [19]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=3)
kfold

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for i in kfold.split([1,2,3,4,5,6,7,8,9]):
    print(i)

(array([3, 4, 5, 6, 7, 8]), array([0, 1, 2]))
(array([0, 1, 2, 6, 7, 8]), array([3, 4, 5]))
(array([0, 1, 2, 3, 4, 5]), array([6, 7, 8]))


In [25]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)
kf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    
    scores_logistic.append(get_score(LogisticRegression(), X_train, y_train, X_test, y_test))
    scores_svm.append(get_score(SVC(), X_train, y_train, X_test, y_test))    
    scores_rf.append(get_score(RandomForestClassifier(), X_train, y_train, X_test, y_test))    

c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [27]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [28]:
scores_rf

[0.9432387312186978, 0.9482470784641068, 0.9232053422370617]

In [29]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [30]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\yashm\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [33]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [34]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.94444444, 0.91111111, 0.96100279, 0.97493036, 0.92479109])

# Parameter tunning using k fold cross validation

In [35]:
scores = cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target)
np.average(scores)

0.9109826679046735

In [36]:
scores = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target)
np.average(scores)

0.9299102445063447

In [37]:
scores = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)
np.average(scores)

0.942137109254101

In [38]:
scores = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)
np.average(scores)

0.9282358402971216